language: node_js
node_js:
  - node
os: osx
install: npm i
cache:
  directories:
    - "$HOME/.npm"
script:
  - npm run build
  - npm run test:coverage:publish
  - npm run build:docs
deploy:
  - provider: releases
    draft: true
    api_key: $GITHUB_TOKEN
    file: theme/astern.zip
    on:
      repo: DBaker85/astern
      branch: main
    skip_cleanup: "true"
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: .docs/astern
    on:
      branch: dev
jobs:
  include:
    - name: "Publish to Chromatic"
      script: travis_wait npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes
